name = "resumedingwang"
compatibility_date = "2024-03-09"
compatibility_flags = ["nodejs_compat"]
main = ".next/server/app/page.js"

[site]
bucket = ".next/static"

[build]
command = "npm run build"
watch_dir = "app"

[env.production]
route = "*/*"
zone_id = "your-zone-id"